---
- name: Manage GNS3 devices
  hosts: GNS3-ALL 
  gather_facts: false
  connection: local

  vars:
    cli:
      username: simon
      password: simon

  tasks:
    - name: enable eigrp
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router eigrp 1
        lines:
          - no auto-summary
          - network 0.0.0.0 0.0.0.0

      register: print_output

    -  debug: var=print_output


