---

- name: Area 0
  hosts: GNS3-AREA0
  gather_facts: false
  connection: local

  vars:
    cli:
      username: simon
      password: simon

  tasks:


    - name: Remove Global config settings
      ios_config:
        provider: "{{ cli }}"
        lines:
          - no ip name-server 8.8.8.8
          - no ip http server
          - no ip http secure-server
          - no snmp-server community python1 RO
          - no snmp-server community python2 RW

          - no clock timezone CET +1
          - no clock summer-time CET recurring
          - no service timestamps debug datetime msec localtime
          - no service timestamps log datetime msec localtime
          - no interface loop 5
          - no interface loop 55

      register: print_output

    - debug: var=print_output

    - name: save memory
      ios_command:
        provider: "{{ cli }}"
        commands:
        - command: 'copy running start'
          prompt: '[confirm]'
          answer: "\r"

      register: print_output

    - debug: var=print_output
