---
- name: Backup show run (enable mode commands)
  hosts: GNS3-ALL
  gather_facts: false
  connection: local

  vars:
  cli:
    username: simon
    password: simon

  tasks:
    - name: run enable level commands
      ios_command:
        provider: "{{ cli }}"
        commands:
          - command: 'show run'

      register: print_output

    - debug: var=print_output.stdout_lines

    - name: save output to a file
      copy:
        content: "{{ print_output.stdout[0] }}"
        dest: "/etc/ansible/config_backups/{{ inventory_hostname }}.txt"


# Description:
# Use the ios commands module to get show run information
# Go to enable mode
# Save the output to files
# http://docs.ansible.com/ansible/latest/ios_command_module.html

# Commands to run:
#1) ansible-playbook shver3.yml -u david -k
