---
- name: Multiple device changes
  hosts: VK05102-3560G-01,VK05102-2960X-01
  gather_facts: false
  connection: local
  vars:
    cli:
      username: sgra
      password: "!!Bik3Rid3!!qwert"

  tasks:
    - name: remove interface
      ios_interface:
        provider: "{{ cli }}"
        authorize: yes
        name: Vlan666
        state: absent

      register: print_output

    -  debug: var=print_output

- name: Switch specific config
  hosts: VK05102-3560G-01
  gather_facts: false
  connection: local
  vars:
    cli:
      username: sgra
      password: "!!Bik3Rid3!!qwert"

  tasks:
    - name: delete Vlan
      ios_vlan:
        provider: "{{ cli }}"
        authorize: yes
        vlan_id: 666
        state: absent

      register: print_output

    -  debug: var=print_output
