---
- name: Get ip Int brief
  hosts: GNS3-ALL
  gather_facts: false

  tasks:
    - name: show ip int brief
      raw: "show ip int brief"
      register: print_output
    -  debug: var=print_output.stdout_lines

